object board_game
object minesweeper

object board {
  id = string *
  flag_available = number
  bombs_available = number
  rows = numbers
  columns = numbers
  'game_timer = number
  'temporizador
}

object cell {
  position = array
  exposed = boolean
  ' withBomb = boolean
  ' flagged = boolean
  ' "cantidad bombas vecinas" = number*
}

' inform quantity of bombs in each cell of the matrix related with their neighbors
object neighbors_bombs_counter {
  position = array
  quantity = number
}

object bomb {
  position = array
}

object flag {
  position = array
}

board_game -> minesweeper
minesweeper *-- board
neighbors_bombs_counter o-- "n" board
bomb o-- "n" board
flag o-- "n" board

board --o "row x column" cell


' Object03 *-- Object04
' Object05 o-- "4" Object06
' Object07 .. Object08 : some labels
